// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdqMbqbEBbp51gj264xbDRjdM477KQD4',
    appId: '1:759862519159:web:027a9aa33ab365ab272d72',
    messagingSenderId: '759862519159',
    projectId: 'agric-solution',
    authDomain: 'agric-solution.firebaseapp.com',
    storageBucket: 'agric-solution.appspot.com',
    measurementId: 'G-ZKH3QYVVSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwXx-eho2WhQyWAnA0XAlj49Z_tSGOoQ',
    appId: '1:759862519159:android:82eda31568a19695272d72',
    messagingSenderId: '759862519159',
    projectId: 'agric-solution',
    storageBucket: 'agric-solution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmB-89e0y80wamp-U9O8aKCUuDcgVp-lE',
    appId: '1:759862519159:ios:372a0673aa5c36c4272d72',
    messagingSenderId: '759862519159',
    projectId: 'agric-solution',
    storageBucket: 'agric-solution.appspot.com',
    iosClientId: '759862519159-gitt6df2b7jg83iqai5o6ngrhlpqve0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.agricSolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmB-89e0y80wamp-U9O8aKCUuDcgVp-lE',
    appId: '1:759862519159:ios:372a0673aa5c36c4272d72',
    messagingSenderId: '759862519159',
    projectId: 'agric-solution',
    storageBucket: 'agric-solution.appspot.com',
    iosClientId: '759862519159-gitt6df2b7jg83iqai5o6ngrhlpqve0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.agricSolution',
  );
}
